#!/usr/bin/env php 

<?php 

use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Speak demo','Version 1');

$app->add(new SpeakCommand);

$app->run();

